### ISSUE TITLE
-save_sgi_params arg is missing from inference script

### ISSUE THREAD

**Issue by danrossi** [jeonchangbin49/De-limiter#2]
There is an immediate error running the tool because of the missing arg. Needs this from the test file

```
parser.add_argument(
        "--save_sgi_params",
        type=str2bool,
        default=False,
        help="Save SGI params for further analysis",
    )
  parser.add_argument(
        "--avoid_clipping",
        type=str2bool,
        default=True,
        help="Forcefully normalize an output by np.abs(wav).max() if there exist some values that exceed 0 dBFS",
    )
```

**Comment by danrossi** [comment]
I don't understand but argparse instead accepting either --data_root ="" or --data_root "" as arguments. So wierd.

**Comment by jeonchangbin49** [comment]
I don't get what you mean. Could you give me the exact errors that you got?

**Comment by jeonchangbin49** [comment]
I think I got confused with test_ddp.py and inference.py. Thanks to @tonyshackell , I guess this issue has been solved. Please re-open this when you get another error.
